(define virtual-keys (make-hash-table))
(populate-virtual-keys! virtual-keys)

(define key-hooks (make-hash-table))
(define add-key-hook! (lambda (key proc)
						(let ((hook-name (string-append "pressed-" key)))
						  (hash-set! key-hooks hook-name (make-hook 0))
						  (add-hook! (hash-ref key-hooks hook-name) proc))))

(define try-key-hook (lambda (key-info)
					   (let ((key (assoc-ref key-info "c")))
						 (if (and key (not (eq? key #\nul)))
							 (begin
							   (let* ((hook-name (string-append "pressed-" (string key)))
									  (h (hash-ref key-hooks hook-name)))
								 (if (hook? h)
									 (run-hook h))))
							 (begin							   
							   (let* ((hook-name (string-append "pressed-" (hash-ref virtual-keys (assoc-ref key-info "vk"))))
									  (h (hash-ref key-hooks hook-name)))
								 (if (hook? h)
									 (run-hook h))))
							   ))))

(add-key-hook! "q" (lambda ()
					 (display "quit!")
					 (newline)
					 (quit)))

(add-key-hook! "up" (lambda ()
					  (display "Up!") (newline)))

(add-key-hook! "f" (lambda ()
					 (if (assoc-ref overlays 'fov)
						 (remove-overlay 'fov)
						 (add-overlay 'fov (lambda ()
											 (for-each (lambda (e)
														 (for-each (lambda (c)
																	 (set-back-colour! (car c) (cdr c) '(100 100 0)))
																   (fov m (position e) 7)))
													   (entities m)))))))

(add-key-hook! "p" (lambda ()
					 (for-each (lambda (e)
								 (libtcod-path-compute (path e) (position e) (random-free-spot m)))
							   (entities m))
					 (remove-overlay 'path)
					 (add-overlay 'path (lambda ()
										  (for-each (lambda (e)
													  (for-each (lambda (c)
																  (set-back-colour! (car c) (cdr c) '(50 0 0)))
																(path->list (path e))))
													(entities m))))))

(add-key-hook! "m" (lambda ()
					 (for-each (lambda (e)
								 (define pos (libtcod-path-walk (path e)))
								 (if pos
									 (set! (position e) pos)))
							   (entities m))))

;; (add-key-hook! "w" (lambda ()
;; 					 (let ((e (car entities)))
;; 					   (push-goal! e (move-goal e (cons (entity-x e) (1- (entity-y e))))))))

;; (add-key-hook! "s" (lambda ()
;; 					 (let ((e (car entities)))
;; 					   (push-goal! e (move-goal e (cons (entity-x e) (1+ (entity-y e))))))))

;; (add-key-hook! "a" (lambda ()
;; 					 (let ((e (car entities)))
;; 					   (push-goal! e (move-goal e (cons (1- (entity-x e)) (entity-y e)))))))

;; (add-key-hook! "d" (lambda ()
;; 					 (let ((e (car entities)))
;; 					   (push-goal! e (move-goal e (cons (1+ (entity-x e)) (entity-y e)))))))

;; (add-key-hook! "r" (lambda ()
;; 					 (let ((e (car entities)))
;; 					   (push-goal! e (move-goal e (map-random-free-spot m))))))
