(define virtual-keys (make-hash-table))
(populate-virtual-keys! virtual-keys)

(define key-hooks (make-hash-table))
(define add-key-hook! (lambda (key proc)
						(let ((hook-name (string-append "pressed-" key)))
						  (hash-set! key-hooks hook-name (make-hook 0))
						  (add-hook! (hash-ref key-hooks hook-name) proc))))

(define try-key-hook (lambda (key-info)
					   (let ((key (assoc-ref key-info "c")))
						 (if (and key (not (eq? key #\nul)))
							 (begin
							   (let* ((hook-name (string-append "pressed-" (string key)))
									  (h (hash-ref key-hooks hook-name)))
								 (if (hook? h)
									 (run-hook h))))
							 (begin							   
							   (let* ((hook-name (string-append "pressed-" (hash-ref virtual-keys (assoc-ref key-info "vk"))))
									  (h (hash-ref key-hooks hook-name)))
								 (if (hook? h)
									 (run-hook h))))
							 ))))

(add-key-hook! " " (lambda ()
					 (set! running (not running))))

(add-key-hook! "q" (lambda ()
					 (if (get-environment-variable "RUNNING_IN_REPL")
						 (set! running #f)
						 (exit))))

(add-key-hook! "f" (lambda ()
					 (for-each (lambda (camera)
								 (if (assoc-ref (overlays camera) 'fov)
									 (remove-overlay! camera 'fov)
									 (add-overlay! camera 'fov (fov-overlay camera))))
							   cameras)))

(add-key-hook! "p" (lambda ()
					 (for-each (lambda (camera)
								 (if (assoc-ref (overlays camera) 'path)
									 (remove-overlay! camera 'path)
									 (add-overlay! camera 'path (path-overlay camera))))
							   cameras)))
